apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: theykk-logger
  namespace: logger
  labels:
    k8s-app: theykk-logger-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      name: theykk-logger
  template:
    metadata:
      labels:
        name: theykk-logger
        k8s-app: theykk-logger-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "false"
    spec:
      containers:
      - name: theykk-logger
        image: theykk.com/library/logger:v0.0.2
        imagePullPolicy: Always
        env:
          - name: MONGO_URI
            valueFrom:
                secretKeyRef:
                  name: theykk-logger
                  key: MONGO_URI
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      serviceAccountName: theykk-logger
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - operator: "Exists"
        effect: "NoExecute"
      - operator: "Exists"
        effect: "NoSchedule"
