apiVersion: v1
kind: Namespace
metadata:
  name: logger
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: theykk-logger
  namespace: logger
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  hostNetwork: true
  privileged: true
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: theykk-logger
  namespace: logger
rules:
- apiGroups: ['*']
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  resourceNames:
  - theykk-logger
  resources:
  - podsecuritypolicies
  verbs:
  - use
