apiVersion: v1
kind: Namespace
metadata:
  name: logger
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: theykk-logger
  namespace: logger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: theykk-logger-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: theykk-logger-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: theykk-logger-read
subjects:
- kind: ServiceAccount
  name: theykk-logger
  namespace: logger
